### ISSUE TITLE
problema riproiezione gdal su F28

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteosatlib#11]
(Disclaimer: non è chiaro in questa fase se sia un bug di meteosatlib o di gdal)

Lo stesso comando di riproiezione da HRIT a geoTiff genera risultati diversi (errati su f28):
```
gdalwarp -q -of 'GTiff' -t_srs '+proj=utm +zone=32 +datum=WGS84' -te 310000 3920000 1314000 5224000 /autofs/scratch2/dbranchini/ricalcolo_indici/20171230/H:MSG3:VIS006r:201712301000 Vis006r24.tif
```
allegato dataset: 
[201712301000.tar.gz](https://github.com/ARPA-SIMC/meteosatlib/files/3137656/201712301000.tar.gz)

e tiff finali con log (nota interessante: il log di f24 è sensibilmente più corto): 
[tif_e_log.tar.gz](https://github.com/ARPA-SIMC/meteosatlib/files/3137661/tif_e_log.tar.gz)

**Comment by dcesari** [comment]
Aggiungendo `-ts 4000 4000` (passo di griglia in m) si ottiene lo stesso risultato, probabilmente se non specifichi quanti punti vuoi usa un default che cambia da gdal a gdal.

**Comment by brancomat** [comment]
Dopo qualche test, parrebbe proprio di sì. Magra figura ma almeno problema risolto.
