### ISSUE TITLE
remove local PublicDecompWT and use public package

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteosatlib#14]
PublicDecompWT is now under Apache 2.0 license:
https://gitlab.eumetsat.int/open-source/PublicDecompWT

RPM packaging files have been created (https://github.com/ARPA-SIMC/PublicDecompWT-rpm) and the package is available in simc/stable copr repo.

meteosatlib shoud use the packaged files and remove the internal "decompress" directory.

@spanezz please note:
I didn't match the multiple subdir structure of the old package, all libs are in `/usr/lib64/PublicDecompWT/` and all headers in `/usr/include/PublicDecompWT` (but I can change it if it's a problem)

**Comment by spanezz** [comment]
I pushed to master a build that uses git submodules. I'll now see about using a system-installed version if present

**Comment by spanezz** [comment]
Now also pushed to master (6de248312a44e97de6f46d5666382dc31706754b) the possibility of building with a system installed version of publicdecompwt.

Note that it needs pkg-config support on publicdecompwt's side. See https://github.com/ARPA-SIMC/PublicDecompWT-rpm/issues/1
