### ISSUE TITLE
Istallation instructions are incomlete/misleading

### ISSUE THREAD

**Issue by CDMIUB** [ARPA-SIMC/meteosatlib#21]
This issue ha two sub-issues:
(i) README.md states that `git checkout --recurse-submodules` is suitable to get the sources and PublicDecompWT. This does not work for me. If I `git clone https://github.com/ARPA-SIMC/meteosatlib.git` and the change to directory meteosatlib, the command `git checkout --recurse-submodules` just returns `head/master is up to date`. Hence I would recommed writing:
"Use `git clone --recurse-submodules https://github.com/ARPA-SIMC/meteosatlib.git` to obtain the sources."
(iI) README.md and INSTALL both state that the sequence `./configure` and `make` would build the binaries, which doesn't work since there is no file named `configure`. To build this the command `autoreconf  autoreconf -ifv` is needed, as can be seen in `.travis-build.sh`, which is not obvious for the average adressee of the installation instructions. I suggest two possible solutions here,  a) distribute a `configure` script file or b) expand the instructions, accordingly.

**Comment by brancomat** [comment]
Thank you for the feedback.
I just updated README.md according to your observations.
