### ISSUE TITLE
MSG4 Meteosat11 files conversion to GRIB

### ISSUE THREAD

**Issue by CrissCama** [ARPA-SIMC/meteosatlib#22]
Buongiorno,
questo issue è per tracciare le modifiche e le discussioni in merito all'elaborazione dei file MSG4 e successiva conversione in GRIB.
Da stato dell'arte, è stato effettuato già un tentativo di conversione di un file MSG4. Potreste postare qui in risposta la stringa esatta dell'errore ricevuto? Il test di conversione è stato provato da riga di comando? Se si potreste postare il comando lanciato con i relativi parametri?
Grazie della vostra disponibilità.

**Comment by brancomat** [comment]
I comandi per conversione in grib sono documentati alla sezione esempi del wiki:
https://github.com/ARPA-SIMC/meteosatlib/wiki/Examples

Esempi:
`$ msat -c MsatGRIB H-000-MSG4__-MSG4________-WV_062___-000007___-202002231100-C_`
o anche:
`$ msat -c MsatGRIB H:MSG4:VIS006:202002231100`

però confermo che sembrano esserci dei problemi con dati MSG4 recenti, ho aperto issue #24 sul tema

**Comment by spanezz** [comment]
Ho fatto commit in master della fix a #24

**Comment by brancomat** [comment]
Nella release v1.12 (già pubblicata) è stata ripristinata la possibilità di trasformare in grib i dati MSG4/Meteosat11.
Chiudo la issue, se servono altre informazioni riapritela pure.
