### ISSUE TITLE
module 'scipy.misc' has no attribute 'imresize'

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteosatlib#23]
(in "examples/products" script)

as stated in https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imresize.html

> imresize is deprecated! imresize is deprecated in SciPy 1.0.0, and will be removed in 1.3.0. Use Pillow instead: numpy.array(Image.fromarray(arr).resize()).

**Comment by spanezz** [comment]
Note: now products requires the `skimage` python package

**Comment by brancomat** [comment]
`python3-scikit-image` is currently unavailable for CentOs8. Since we're already using `python3-pillow` can we switch to that?
