### ISSUE TITLE
msat-view: no module named 'gobject'

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteosatlib#27]
```
$ msat-view H-000-MSG3__-MSG3_RSS____-WV_062___-000007___-202011161255-C_
Traceback (most recent call last):
  File "/usr/bin/msat-view", line 404, in <module>
    start_app()
  File "/usr/bin/msat-view", line 26, in start_app
    import gobject
ModuleNotFoundError: No module named 'gobject'
```
both `python3-gobject` and `python3-gobject-base` are present on the system.

**Comment by spanezz** [comment]
Ah, very nice, the python Gtk API has changed massively (again).

I'll try porting it to the new Gtk.

**Comment by spanezz** [comment]
Replace porting with rewriting :(

**Comment by spanezz** [comment]
I've done the rewrite, and I've also added mouse-wheel zoom. I'm not sure if with the new Gtk it'll work on older distributions, I hope so. If not, we can ship both implementations, I guess?

If you'd like changes or new features in the interface, let me know while I still have Gtk details in mind.
