### ISSUE TITLE
[Fedora 38] Build errors

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteosatlib#35]
some `error: 'uint8_t' does not name a type` followed by `'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?`

Full log:
https://simc.arpae.it/moncic-ci/meteosatlib/202305250700/master/fedora38/build.log

**Comment by edigiacomo** [comment]
Fixed in a8fa6c0.
