### ISSUE TITLE
Remove SAFH5 support

### ISSUE THREAD

**Issue by spanezz** [ARPA-SIMC/meteosatlib#4]
Since SAF HDF5 files contain products derived from satellite images but not satellite images, much of what meteosatlib provides over plain GDAL (like sensor channel number) becomes irrelevant.

If plain GDAL is enough for plotting and georeferencing, I would like to remove SAF HDF5 support in Meteosatlib.

I'm opening this issue to track verification of details, and if we have the go ahead, removal of the SAFH5 code.

**Comment by brancomat** [comment]
Yes, plain gdal-python scripts are enough for SAF HDF5 data management
