### ISSUE TITLE
Rocky 8 build failure: error: 'filesystem' is not a member of 'std'

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/meteosatlib#40]
See https://simc.arpae.it/moncic-ci/meteosatlib/202410181430/master/rocky8/build.log

I think this is the same issue encountered in wreport c++17, fixed in meson.build with 

```
# std::filesystem library needs to be explicitly linked with g++ < 9.0
if cpp.find_library('stdc++fs').found()
  # without this, std::filesystem is not present for some compilers
  add_project_link_arguments(['-lstdc++fs'], language : 'cpp')
endif
```

But I don't know a quick fix in autotools.

**Comment by spanezz** [comment]
I started a `meson` branch porting meteosatlib to meson.

Code builds and tests pass. Tomorrow I'll try to look into installation and packaging

**Comment by spanezz** [comment]
I opened #41 with meteosatlib build system ported to Meson

**Comment by brancomat** [comment]
meteosatlib v1.17 meson-built is now released
